workers: 
  transport: vumi.transports.telnet.TelnetServerTransport
  reverse_app: shoprite.app.ShopriteAppWorker

transport: 
  transport_name: reverse
  telnet_port: 9001

reverse_app: 
  transport_name: reverse

